[tool.poetry]
name = "snaptrade-python-sdk"
version = "11.0.80"
description = "Client for SnapTrade"
authors = ["SnapTrade <api@snaptrade.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "snaptrade_client"}]

[tool.poetry.dependencies]
python = "^3.8"
certifi = ">=2023.7.22"
python-dateutil = "^2.8.2"
typing_extensions = "^4.3.0"
urllib3 = "^1.26.18 || ^2.0.0"
cryptography = "^43.0.3"
frozendict = "^2.3.4"
aiohttp = "^3.10.11"

[tool.poetry.group.dev.dependencies]
setuptools = "^65.5.1"
pytest = "^7.3.1"
pytest-cov = "2.8.1"
pytest-randomly = "1.2.3"
build = "^0.10.0"
pytest-asyncio = "^0.21.0"
black = "^23.3.0"
twine = "^6.1.0"
docutils = "^0.20.1"

[build-system]
requires = ["poetry-core<1.7.0"]
build-backend = "poetry.core.masonry.api"
