/*
 * SnapTrade
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.snaptrade.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.snaptrade.client.JSON;

/**
 * Estimated cash change and fees for an option order before it is placed.
 */
@ApiModel(description = "Estimated cash change and fees for an option order before it is placed.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class OptionImpact {
  public static final String SERIALIZED_NAME_ESTIMATED_CASH_CHANGE = "estimated_cash_change";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_CASH_CHANGE)
  private String estimatedCashChange;

  /**
   * Direction of the cash change. CREDIT means cash is received, DEBIT means cash is paid out, EVEN means no cash changes hands. UNKNOWN if the direction cannot be determined from the request.
   */
  @JsonAdapter(CashChangeDirectionEnum.Adapter.class)
 public enum CashChangeDirectionEnum {
    CREDIT("CREDIT"),
    
    DEBIT("DEBIT"),
    
    EVEN("EVEN"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    CashChangeDirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CashChangeDirectionEnum fromValue(String value) {
      for (CashChangeDirectionEnum b : CashChangeDirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CashChangeDirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CashChangeDirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CashChangeDirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CashChangeDirectionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CASH_CHANGE_DIRECTION = "cash_change_direction";
  @SerializedName(SERIALIZED_NAME_CASH_CHANGE_DIRECTION)
  private CashChangeDirectionEnum cashChangeDirection;

  public static final String SERIALIZED_NAME_ESTIMATED_FEE_TOTAL = "estimated_fee_total";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_FEE_TOTAL)
  private String estimatedFeeTotal;

  public OptionImpact() {
  }

  public OptionImpact estimatedCashChange(String estimatedCashChange) {
    
    
    
    
    this.estimatedCashChange = estimatedCashChange;
    return this;
  }

   /**
   * Estimated cash change for the order, before fees.
   * @return estimatedCashChange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.97", value = "Estimated cash change for the order, before fees.")

  public String getEstimatedCashChange() {
    return estimatedCashChange;
  }


  public void setEstimatedCashChange(String estimatedCashChange) {
    
    
    
    this.estimatedCashChange = estimatedCashChange;
  }


  public OptionImpact cashChangeDirection(CashChangeDirectionEnum cashChangeDirection) {
    
    
    
    
    this.cashChangeDirection = cashChangeDirection;
    return this;
  }

   /**
   * Direction of the cash change. CREDIT means cash is received, DEBIT means cash is paid out, EVEN means no cash changes hands. UNKNOWN if the direction cannot be determined from the request.
   * @return cashChangeDirection
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Direction of the cash change. CREDIT means cash is received, DEBIT means cash is paid out, EVEN means no cash changes hands. UNKNOWN if the direction cannot be determined from the request.")

  public CashChangeDirectionEnum getCashChangeDirection() {
    return cashChangeDirection;
  }


  public void setCashChangeDirection(CashChangeDirectionEnum cashChangeDirection) {
    
    
    
    this.cashChangeDirection = cashChangeDirection;
  }


  public OptionImpact estimatedFeeTotal(String estimatedFeeTotal) {
    
    
    
    
    this.estimatedFeeTotal = estimatedFeeTotal;
    return this;
  }

   /**
   * Estimated total transaction fees and commissions for the order.
   * @return estimatedFeeTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.50", value = "Estimated total transaction fees and commissions for the order.")

  public String getEstimatedFeeTotal() {
    return estimatedFeeTotal;
  }


  public void setEstimatedFeeTotal(String estimatedFeeTotal) {
    
    
    
    this.estimatedFeeTotal = estimatedFeeTotal;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the OptionImpact instance itself
   */
  public OptionImpact putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptionImpact optionImpact = (OptionImpact) o;
    return Objects.equals(this.estimatedCashChange, optionImpact.estimatedCashChange) &&
        Objects.equals(this.cashChangeDirection, optionImpact.cashChangeDirection) &&
        Objects.equals(this.estimatedFeeTotal, optionImpact.estimatedFeeTotal)&&
        Objects.equals(this.additionalProperties, optionImpact.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(estimatedCashChange, cashChangeDirection, estimatedFeeTotal, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptionImpact {\n");
    sb.append("    estimatedCashChange: ").append(toIndentedString(estimatedCashChange)).append("\n");
    sb.append("    cashChangeDirection: ").append(toIndentedString(cashChangeDirection)).append("\n");
    sb.append("    estimatedFeeTotal: ").append(toIndentedString(estimatedFeeTotal)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("estimated_cash_change");
    openapiFields.add("cash_change_direction");
    openapiFields.add("estimated_fee_total");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OptionImpact
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OptionImpact.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OptionImpact is not found in the empty JSON string", OptionImpact.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("estimated_cash_change") != null && !jsonObj.get("estimated_cash_change").isJsonNull()) && !jsonObj.get("estimated_cash_change").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `estimated_cash_change` to be a primitive type in the JSON string but got `%s`", jsonObj.get("estimated_cash_change").toString()));
      }
      if (!jsonObj.get("cash_change_direction").isJsonNull() && (jsonObj.get("cash_change_direction") != null && !jsonObj.get("cash_change_direction").isJsonNull()) && !jsonObj.get("cash_change_direction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cash_change_direction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cash_change_direction").toString()));
      }
      if ((jsonObj.get("estimated_fee_total") != null && !jsonObj.get("estimated_fee_total").isJsonNull()) && !jsonObj.get("estimated_fee_total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `estimated_fee_total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("estimated_fee_total").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OptionImpact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OptionImpact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OptionImpact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OptionImpact.class));

       return (TypeAdapter<T>) new TypeAdapter<OptionImpact>() {
           @Override
           public void write(JsonWriter out, OptionImpact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null) {
                   obj.addProperty(entry.getKey(), (String) null);
                 } else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public OptionImpact read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             OptionImpact instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OptionImpact given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OptionImpact
  * @throws IOException if the JSON string is invalid with respect to OptionImpact
  */
  public static OptionImpact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OptionImpact.class);
  }

 /**
  * Convert an instance of OptionImpact to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

