<?php
/**
 * NotionalValueTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * NotionalValueTest Class Doc Comment
 *
 * @category    Class
 * @description Total notional amount for the order. Must be &#x60;null&#x60; if &#x60;units&#x60; is provided. Can only work with &#x60;Market&#x60; for &#x60;order_type&#x60; and &#x60;Day&#x60; for &#x60;time_in_force&#x60;. This is only available for certain brokerages. Please check the [integrations doc](https://support.snaptrade.com/brokerages-table?v&#x3D;e7bbcbf9f272441593f93decde660687) for more information.
 * @package     SnapTrade
 */
class NotionalValueTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "NotionalValue"
     */
    public function testNotionalValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
