<?php
/**
 * OrderTypeStrictTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SnapTrade
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


namespace SnapTrade\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderTypeStrictTest Class Doc Comment
 *
 * @category    Class
 * @description The type of order to place.  - For &#x60;Limit&#x60; and &#x60;StopLimit&#x60; orders, the &#x60;price&#x60; field is required. - For &#x60;Stop&#x60; and &#x60;StopLimit&#x60; orders, the &#x60;stop&#x60; field is required.
 * @package     SnapTrade
 */
class OrderTypeStrictTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderTypeStrict"
     */
    public function testOrderTypeStrict()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
