/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

The version of the OpenAPI document: 1.0.0
Contact: api@snaptrade.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountSyncStatus } from './account-sync-status';
import { Balance } from './balance';
import { Brokerage } from './brokerage';
import { BrokerageAuthorization } from './brokerage-authorization';
import { BrokerageType } from './brokerage-type';
import { Currency } from './currency';
import { Exchange } from './exchange';
import { Position } from './position';
import { PositionSymbol } from './position-symbol';
import { SecurityType } from './security-type';
import { SnapTradeHoldingsAccount } from './snap-trade-holdings-account';
import { SnapTradeHoldingsTotalValue } from './snap-trade-holdings-total-value';
import { UniversalSymbol } from './universal-symbol';

/**
 * Account Holdings
 * @export
 * @interface AccountHoldings
 */
export interface AccountHoldings {
    [key: string]: any;

    /**
     * 
     * @type {SnapTradeHoldingsAccount}
     * @memberof AccountHoldings
     */
    'account'?: SnapTradeHoldingsAccount;
    /**
     * 
     * @type {Array<Balance>}
     * @memberof AccountHoldings
     */
    'balances'?: Array<Balance> | null;
    /**
     * 
     * @type {Array<Position>}
     * @memberof AccountHoldings
     */
    'positions'?: Array<Position> | null;
    /**
     * 
     * @type {SnapTradeHoldingsTotalValue}
     * @memberof AccountHoldings
     */
    'total_value'?: SnapTradeHoldingsTotalValue;
}

