/* tslint:disable */
/* eslint-disable */
/**
 * SnapTrade
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * Trade Action
 * @export
 * @enum {string}
 */

export const Action = {
    Buy: 'BUY',
    Sell: 'SELL'
} as const;

export type Action = typeof Action[keyof typeof Action];



