/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

The version of the OpenAPI document: 1.0.0
Contact: api@snaptrade.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ConnectionAccountSyncStatus } from './connection-account-sync-status';
import { DepositAccount } from './deposit-account';
import { DepositAccountBalance } from './deposit-account-balance';
import { InvestmentAccount } from './investment-account';
import { InvestmentAccountMarketValue } from './investment-account-market-value';

/**
 * @type ConnectionAccount
 * A single account under a connection, from the `kind`-discriminated union used by `Connections_listConnectionAccounts`. Use `kind` to determine which schema is present.  `investment` and `deposit` are implemented today; `line_of_credit` will be added as an additional variant in a future release. 
 * @export
 */
export type ConnectionAccount = { kind: 'deposit' } & DepositAccount | { kind: 'investment' } & InvestmentAccount;


