/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

The version of the OpenAPI document: 1.0.0
Contact: api@snaptrade.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountOrderRecord } from './account-order-record';

/**
 * 
 * @export
 * @interface OrderUpdatedResponse
 */
export interface OrderUpdatedResponse {
    [key: string]: any;

    /**
     * Order ID returned by brokerage. This is the unique identifier for the order in the brokerage system.
     * @type {string}
     * @memberof OrderUpdatedResponse
     */
    'brokerage_order_id': string;
    /**
     * 
     * @type {AccountOrderRecord}
     * @memberof OrderUpdatedResponse
     */
    'order'?: AccountOrderRecord;
}

