/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

The version of the OpenAPI document: 1.0.0
Contact: api@snaptrade.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Individual rate of return object with return percent and timeframe
 * @export
 * @interface RateOfReturnObject
 */
export interface RateOfReturnObject {
    [key: string]: any;

    /**
     * The timeframe this return percent is reflecting
     * @type {string}
     * @memberof RateOfReturnObject
     */
    'timeframe'?: RateOfReturnObjectTimeframeEnum;
    /**
     * The percent return of the portfolio, directly from the brokerage. 5.97 indicates a 5.97% return over the timeframe
     * @type {number}
     * @memberof RateOfReturnObject
     */
    'return_percent'?: number;
    /**
     * The date this was fetched
     * @type {string}
     * @memberof RateOfReturnObject
     */
    'created_date'?: string;
}

type RateOfReturnObjectTimeframeEnum = 'ALL' | '1Y' | '6M' | '3M' | '1M'


