/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

The version of the OpenAPI document: 1.0.0
Contact: api@snaptrade.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TradeDetectionCancelSubscriptionResponse
 */
export interface TradeDetectionCancelSubscriptionResponse {
    [key: string]: any;

    /**
     * 
     * @type {boolean}
     * @memberof TradeDetectionCancelSubscriptionResponse
     */
    'success': boolean;
}

