/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SnapTrade.Net.Api;
using SnapTrade.Net.Model;
using SnapTrade.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SnapTrade.Net.Test.Model
{
    /// <summary>
    ///  Class for testing BrokerageAuthorization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrokerageAuthorizationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrokerageAuthorization
        //private BrokerageAuthorization instance;

        public BrokerageAuthorizationTests()
        {
            // TODO uncomment below to create an instance of BrokerageAuthorization
            //instance = new BrokerageAuthorization();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrokerageAuthorization
        /// </summary>
        [Fact]
        public void BrokerageAuthorizationInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrokerageAuthorization
            //Assert.IsType<BrokerageAuthorization>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'UpdatedDate'
        /// </summary>
        [Fact]
        public void UpdatedDateTest()
        {
            // TODO unit test for the property 'UpdatedDate'
        }
        /// <summary>
        /// Test the property 'Brokerage'
        /// </summary>
        [Fact]
        public void BrokerageTest()
        {
            // TODO unit test for the property 'Brokerage'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
        /// <summary>
        /// Test the property 'DisabledDate'
        /// </summary>
        [Fact]
        public void DisabledDateTest()
        {
            // TODO unit test for the property 'DisabledDate'
        }
        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
