/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SnapTrade.Net.Api;
using SnapTrade.Net.Model;
using SnapTrade.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SnapTrade.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Symbol
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SymbolTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Symbol
        //private Symbol instance;

        public SymbolTests()
        {
            // TODO uncomment below to create an instance of Symbol
            //instance = new Symbol();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Symbol
        /// </summary>
        [Fact]
        public void SymbolInstanceTest()
        {
            // TODO uncomment below to test "IsType" Symbol
            //Assert.IsType<Symbol>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property '_Symbol'
        /// </summary>
        [Fact]
        public void _SymbolTest()
        {
            // TODO unit test for the property '_Symbol'
        }
        /// <summary>
        /// Test the property 'RawSymbol'
        /// </summary>
        [Fact]
        public void RawSymbolTest()
        {
            // TODO unit test for the property 'RawSymbol'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Fact]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
