/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SnapTrade.Net.Api;
using SnapTrade.Net.Model;
using SnapTrade.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SnapTrade.Net.Test.Model
{
    /// <summary>
    ///  Class for testing TradeImpact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradeImpactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TradeImpact
        //private TradeImpact instance;

        public TradeImpactTests()
        {
            // TODO uncomment below to create an instance of TradeImpact
            //instance = new TradeImpact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TradeImpact
        /// </summary>
        [Fact]
        public void TradeImpactInstanceTest()
        {
            // TODO uncomment below to test "IsType" TradeImpact
            //Assert.IsType<TradeImpact>(instance);
        }


        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'RemainingCash'
        /// </summary>
        [Fact]
        public void RemainingCashTest()
        {
            // TODO unit test for the property 'RemainingCash'
        }
        /// <summary>
        /// Test the property 'EstimatedCommissions'
        /// </summary>
        [Fact]
        public void EstimatedCommissionsTest()
        {
            // TODO unit test for the property 'EstimatedCommissions'
        }
        /// <summary>
        /// Test the property 'ForexFees'
        /// </summary>
        [Fact]
        public void ForexFeesTest()
        {
            // TODO unit test for the property 'ForexFees'
        }

    }

}
