/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SnapTrade.Net.Api;
using SnapTrade.Net.Model;
using SnapTrade.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SnapTrade.Net.Test.Model
{
    /// <summary>
    ///  Class for testing UserAumPercentileResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAumPercentileResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAumPercentileResponse
        //private UserAumPercentileResponse instance;

        public UserAumPercentileResponseTests()
        {
            // TODO uncomment below to create an instance of UserAumPercentileResponse
            //instance = new UserAumPercentileResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAumPercentileResponse
        /// </summary>
        [Fact]
        public void UserAumPercentileResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAumPercentileResponse
            //Assert.IsType<UserAumPercentileResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
