/*
SnapTrade

Connect brokerage accounts to your app for live positions and trading

API version: 1.0.0
Contact: api@snaptrade.com
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package snaptrade

import (
	"encoding/json"
)

// StockInstrumentFigiInstrument struct for StockInstrumentFigiInstrument
type StockInstrumentFigiInstrument struct {
	// This identifier is unique per security per trading venue. See section 1.4.1 of the [FIGI Standard](https://www.openfigi.com/assets/local/figi-allocation-rules.pdf) for more information.
	FigiCode NullableString `json:"figi_code,omitempty"`
	// This enables users to link multiple FIGIs for the same security in order to obtain an aggregated view across all countries and all exchanges. For example, `AAPL` has a different FIGI for each exchange/trading venue it is traded on. The `figi_share_class` is the same for all of these FIGIs. See section 1.4.3 of the [FIGI Standard](https://www.openfigi.com/assets/local/figi-allocation-rules.pdf) for more information.
	FigiShareClass NullableString `json:"figi_share_class,omitempty"`
}

// NewStockInstrumentFigiInstrument instantiates a new StockInstrumentFigiInstrument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStockInstrumentFigiInstrument() *StockInstrumentFigiInstrument {
	this := StockInstrumentFigiInstrument{}
	return &this
}

// NewStockInstrumentFigiInstrumentWithDefaults instantiates a new StockInstrumentFigiInstrument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStockInstrumentFigiInstrumentWithDefaults() *StockInstrumentFigiInstrument {
	this := StockInstrumentFigiInstrument{}
	return &this
}

// GetFigiCode returns the FigiCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StockInstrumentFigiInstrument) GetFigiCode() string {
	if o == nil || isNil(o.FigiCode.Get()) {
		var ret string
		return ret
	}
	return *o.FigiCode.Get()
}

// GetFigiCodeOk returns a tuple with the FigiCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StockInstrumentFigiInstrument) GetFigiCodeOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.FigiCode.Get(), o.FigiCode.IsSet()
}

// HasFigiCode returns a boolean if a field has been set.
func (o *StockInstrumentFigiInstrument) HasFigiCode() bool {
	if o != nil && o.FigiCode.IsSet() {
		return true
	}

	return false
}

// SetFigiCode gets a reference to the given NullableString and assigns it to the FigiCode field.
func (o *StockInstrumentFigiInstrument) SetFigiCode(v string) {
	o.FigiCode.Set(&v)
}
// SetFigiCodeNil sets the value for FigiCode to be an explicit nil
func (o *StockInstrumentFigiInstrument) SetFigiCodeNil() {
	o.FigiCode.Set(nil)
}

// UnsetFigiCode ensures that no value is present for FigiCode, not even an explicit nil
func (o *StockInstrumentFigiInstrument) UnsetFigiCode() {
	o.FigiCode.Unset()
}

// GetFigiShareClass returns the FigiShareClass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StockInstrumentFigiInstrument) GetFigiShareClass() string {
	if o == nil || isNil(o.FigiShareClass.Get()) {
		var ret string
		return ret
	}
	return *o.FigiShareClass.Get()
}

// GetFigiShareClassOk returns a tuple with the FigiShareClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StockInstrumentFigiInstrument) GetFigiShareClassOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.FigiShareClass.Get(), o.FigiShareClass.IsSet()
}

// HasFigiShareClass returns a boolean if a field has been set.
func (o *StockInstrumentFigiInstrument) HasFigiShareClass() bool {
	if o != nil && o.FigiShareClass.IsSet() {
		return true
	}

	return false
}

// SetFigiShareClass gets a reference to the given NullableString and assigns it to the FigiShareClass field.
func (o *StockInstrumentFigiInstrument) SetFigiShareClass(v string) {
	o.FigiShareClass.Set(&v)
}
// SetFigiShareClassNil sets the value for FigiShareClass to be an explicit nil
func (o *StockInstrumentFigiInstrument) SetFigiShareClassNil() {
	o.FigiShareClass.Set(nil)
}

// UnsetFigiShareClass ensures that no value is present for FigiShareClass, not even an explicit nil
func (o *StockInstrumentFigiInstrument) UnsetFigiShareClass() {
	o.FigiShareClass.Unset()
}

func (o StockInstrumentFigiInstrument) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FigiCode.IsSet() {
		toSerialize["figi_code"] = o.FigiCode.Get()
	}
	if o.FigiShareClass.IsSet() {
		toSerialize["figi_share_class"] = o.FigiShareClass.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableStockInstrumentFigiInstrument struct {
	value *StockInstrumentFigiInstrument
	isSet bool
}

func (v NullableStockInstrumentFigiInstrument) Get() *StockInstrumentFigiInstrument {
	return v.value
}

func (v *NullableStockInstrumentFigiInstrument) Set(val *StockInstrumentFigiInstrument) {
	v.value = val
	v.isSet = true
}

func (v NullableStockInstrumentFigiInstrument) IsSet() bool {
	return v.isSet
}

func (v *NullableStockInstrumentFigiInstrument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStockInstrumentFigiInstrument(val *StockInstrumentFigiInstrument) *NullableStockInstrumentFigiInstrument {
	return &NullableStockInstrumentFigiInstrument{value: val, isSet: true}
}

func (v NullableStockInstrumentFigiInstrument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStockInstrumentFigiInstrument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


