/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SnapTrade.Net.Client.OpenAPIDateConverter;

namespace SnapTrade.Net.Model
{
    /// <summary>
    /// Indicates the status of an order. SnapTrade does a best effort to map brokerage statuses to statuses in this enum.
    /// </summary>
    /// <value>Indicates the status of an order. SnapTrade does a best effort to map brokerage statuses to statuses in this enum.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountOrderRecordStatusV2
    {
        /// <summary>
        /// Enum PENDING for value: PENDING
        /// </summary>
        [EnumMember(Value = "PENDING")]
        PENDING = 1,

        /// <summary>
        /// Enum REJECTED for value: REJECTED
        /// </summary>
        [EnumMember(Value = "REJECTED")]
        REJECTED = 2,

        /// <summary>
        /// Enum CANCELED for value: CANCELED
        /// </summary>
        [EnumMember(Value = "CANCELED")]
        CANCELED = 3,

        /// <summary>
        /// Enum CANCELPENDING for value: CANCEL_PENDING
        /// </summary>
        [EnumMember(Value = "CANCEL_PENDING")]
        CANCELPENDING = 4,

        /// <summary>
        /// Enum PARTIALCANCELED for value: PARTIAL_CANCELED
        /// </summary>
        [EnumMember(Value = "PARTIAL_CANCELED")]
        PARTIALCANCELED = 5,

        /// <summary>
        /// Enum EXECUTED for value: EXECUTED
        /// </summary>
        [EnumMember(Value = "EXECUTED")]
        EXECUTED = 6,

        /// <summary>
        /// Enum PARTIALLYEXECUTED for value: PARTIALLY_EXECUTED
        /// </summary>
        [EnumMember(Value = "PARTIALLY_EXECUTED")]
        PARTIALLYEXECUTED = 7,

        /// <summary>
        /// Enum REPLACED for value: REPLACED
        /// </summary>
        [EnumMember(Value = "REPLACED")]
        REPLACED = 8,

        /// <summary>
        /// Enum REPLACEPENDING for value: REPLACE_PENDING
        /// </summary>
        [EnumMember(Value = "REPLACE_PENDING")]
        REPLACEPENDING = 9,

        /// <summary>
        /// Enum EXPIRED for value: EXPIRED
        /// </summary>
        [EnumMember(Value = "EXPIRED")]
        EXPIRED = 10

    }

}
