/*
 * SnapTrade
 *
 * Connect brokerage accounts to your app for live positions and trading
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@snaptrade.com
 * Generated by: https://konfigthis.com
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SnapTrade.Net.Client.OpenAPIDateConverter;
using System.Reflection;

namespace SnapTrade.Net.Model
{
    /// <summary>
    /// Instrument metadata for a V2 position. Use &#x60;kind&#x60; to determine which schema is present.
    /// </summary>
    [JsonConverter(typeof(InstrumentJsonConverter))]
    [DataContract(Name = "Instrument")]
    public partial class Instrument : AbstractOpenAPISchema, IEquatable<Instrument>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="StockInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of StockInstrument.</param>
        public Instrument(StockInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="OptionInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OptionInstrument.</param>
        public Instrument(OptionInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="CryptoInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CryptoInstrument.</param>
        public Instrument(CryptoInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="FutureInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FutureInstrument.</param>
        public Instrument(FutureInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="EtfInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EtfInstrument.</param>
        public Instrument(EtfInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="MutualFundInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of MutualFundInstrument.</param>
        public Instrument(MutualFundInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="CefInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CefInstrument.</param>
        public Instrument(CefInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="AdrInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AdrInstrument.</param>
        public Instrument(AdrInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="CfdInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CfdInstrument.</param>
        public Instrument(CfdInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Instrument" /> class
        /// with the <see cref="OtherInstrument" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OtherInstrument.</param>
        public Instrument(OtherInstrument actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AdrInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CefInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CfdInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CryptoInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EtfInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(FutureInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(MutualFundInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OptionInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OtherInstrument))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(StockInstrument))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AdrInstrument, CefInstrument, CfdInstrument, CryptoInstrument, EtfInstrument, FutureInstrument, MutualFundInstrument, OptionInstrument, OtherInstrument, StockInstrument");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `StockInstrument`. If the actual instance is not `StockInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of StockInstrument</returns>
        public StockInstrument GetStockInstrument()
        {
            return (StockInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `OptionInstrument`. If the actual instance is not `OptionInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OptionInstrument</returns>
        public OptionInstrument GetOptionInstrument()
        {
            return (OptionInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CryptoInstrument`. If the actual instance is not `CryptoInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CryptoInstrument</returns>
        public CryptoInstrument GetCryptoInstrument()
        {
            return (CryptoInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `FutureInstrument`. If the actual instance is not `FutureInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FutureInstrument</returns>
        public FutureInstrument GetFutureInstrument()
        {
            return (FutureInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EtfInstrument`. If the actual instance is not `EtfInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EtfInstrument</returns>
        public EtfInstrument GetEtfInstrument()
        {
            return (EtfInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `MutualFundInstrument`. If the actual instance is not `MutualFundInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of MutualFundInstrument</returns>
        public MutualFundInstrument GetMutualFundInstrument()
        {
            return (MutualFundInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CefInstrument`. If the actual instance is not `CefInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CefInstrument</returns>
        public CefInstrument GetCefInstrument()
        {
            return (CefInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AdrInstrument`. If the actual instance is not `AdrInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AdrInstrument</returns>
        public AdrInstrument GetAdrInstrument()
        {
            return (AdrInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CfdInstrument`. If the actual instance is not `CfdInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CfdInstrument</returns>
        public CfdInstrument GetCfdInstrument()
        {
            return (CfdInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `OtherInstrument`. If the actual instance is not `OtherInstrument`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OtherInstrument</returns>
        public OtherInstrument GetOtherInstrument()
        {
            return (OtherInstrument)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Instrument {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, Instrument.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of Instrument
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Instrument</returns>
        public static Instrument FromJson(string jsonString)
        {
            Instrument newInstrument = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newInstrument;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(AdrInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<AdrInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<AdrInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("AdrInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AdrInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CefInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CefInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CefInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CefInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CefInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CfdInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CfdInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CfdInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CfdInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CfdInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CryptoInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CryptoInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<CryptoInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CryptoInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CryptoInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EtfInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<EtfInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<EtfInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EtfInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EtfInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(FutureInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<FutureInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<FutureInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("FutureInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FutureInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(MutualFundInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<MutualFundInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<MutualFundInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("MutualFundInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into MutualFundInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OptionInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<OptionInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<OptionInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OptionInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OptionInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OtherInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<OtherInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<OtherInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OtherInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OtherInstrument: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(StockInstrument).GetProperty("AdditionalProperties") == null)
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<StockInstrument>(jsonString, Instrument.SerializerSettings));
                }
                else
                {
                    newInstrument = new Instrument(JsonConvert.DeserializeObject<StockInstrument>(jsonString, Instrument.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("StockInstrument");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into StockInstrument: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newInstrument;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Instrument);
        }

        /// <summary>
        /// Returns true if Instrument instances are equal
        /// </summary>
        /// <param name="input">Instance of Instrument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Instrument input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for Instrument
    /// </summary>
    public class InstrumentJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(Instrument).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return Instrument.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
