name: Detect SDK submodules
description: Determines which SDKs are Git submodules
outputs:
  dirs:
    description: Space-delimited SDK submodule directories
    value: ${{ steps.detect.outputs.dirs }}
runs:
  using: composite
  steps:
    - name: Detect SDK submodules
      id: detect
      shell: bash
      run: echo "dirs=$(konfig list-sdk-submodules | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
