# coding: utf-8

"""
    SnapTrade

    Connect brokerage accounts to your app for live positions and trading  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: api@snaptrade.com
    Generated by: https://konfigthis.com
"""

import unittest

import snaptrade_client
from snaptrade_client.model.trade_impact import TradeImpact
from snaptrade_client import configuration


class TestTradeImpact(unittest.TestCase):
    """TradeImpact unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
