# coding: utf-8

"""
    SnapTrade

    Connect brokerage accounts to your app for live positions and trading

    The version of the OpenAPI document: 1.0.0
    Contact: api@snaptrade.com
    Created by: https://snaptrade.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snaptrade_client import schemas  # noqa: F401


class OptionQuote(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Real-time quote for a single option contract.
    """


    class MetaOapg:
        
        class properties:
            symbol = schemas.StrSchema
            synthetic_price = schemas.NumberSchema
            implied_volatility = schemas.NumberSchema
            
            
            class timestamp(
                schemas.DateTimeBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, datetime, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'timestamp':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
        
            @staticmethod
            def greeks() -> typing.Type['OptionQuoteGreeks']:
                return OptionQuoteGreeks
            __annotations__ = {
                "symbol": symbol,
                "synthetic_price": synthetic_price,
                "implied_volatility": implied_volatility,
                "timestamp": timestamp,
                "greeks": greeks,
            }
        additional_properties = schemas.AnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["synthetic_price"]) -> MetaOapg.properties.synthetic_price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["implied_volatility"]) -> MetaOapg.properties.implied_volatility: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["greeks"]) -> 'OptionQuoteGreeks': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> MetaOapg.additional_properties: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["symbol"], typing_extensions.Literal["synthetic_price"], typing_extensions.Literal["implied_volatility"], typing_extensions.Literal["timestamp"], typing_extensions.Literal["greeks"], str, ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbol"]) -> typing.Union[MetaOapg.properties.symbol, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["synthetic_price"]) -> typing.Union[MetaOapg.properties.synthetic_price, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["implied_volatility"]) -> typing.Union[MetaOapg.properties.implied_volatility, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> typing.Union[MetaOapg.properties.timestamp, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["greeks"]) -> typing.Union['OptionQuoteGreeks', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[MetaOapg.additional_properties, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["symbol"], typing_extensions.Literal["synthetic_price"], typing_extensions.Literal["implied_volatility"], typing_extensions.Literal["timestamp"], typing_extensions.Literal["greeks"], str, ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        symbol: typing.Union[MetaOapg.properties.symbol, str, schemas.Unset] = schemas.unset,
        synthetic_price: typing.Union[MetaOapg.properties.synthetic_price, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        implied_volatility: typing.Union[MetaOapg.properties.implied_volatility, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        timestamp: typing.Union[MetaOapg.properties.timestamp, None, str, datetime, schemas.Unset] = schemas.unset,
        greeks: typing.Union['OptionQuoteGreeks', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
    ) -> 'OptionQuote':
        return super().__new__(
            cls,
            *args,
            symbol=symbol,
            synthetic_price=synthetic_price,
            implied_volatility=implied_volatility,
            timestamp=timestamp,
            greeks=greeks,
            _configuration=_configuration,
            **kwargs,
        )

from snaptrade_client.model.option_quote_greeks import OptionQuoteGreeks
