name: konfig-lint-openapi-spec
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
jobs:
  konfig-lint-openapi-spec: # make sure spec passes konfig lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Konfig CLI
        uses: passiv/konfig-workflows/.github/actions/install-cli@main

      - name: Lint OpenAPI Spec
        run: konfig lint api.yaml
