name: Regenerate SDKs Manually

on:
  workflow_dispatch:
    inputs:
      changeset_type:
        description: Semver bump to use for the generated SDK changeset
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      changeset_message:
        description: Description to use for the generated SDK changeset
        required: true
        type: string

jobs:
  regenerate-sdks-manual:
    permissions:
      contents: write
      pull-requests: write
    uses: passiv/konfig-workflows/.github/workflows/regenerate-sdks.yaml@main
    with:
      konfig_yaml_dir: ./
      changeset_type: ${{ inputs.changeset_type }}
      changeset_message: ${{ inputs.changeset_message }}
      base_branch: master
      head_branch: sdk-regeneration/manual-${{ github.run_id }}
      create_pull_request: true
      pull_request_title: Regenerate SDKs
      pull_request_body: |
        Manually triggered SDK regeneration from ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.

        Changeset type: ${{ inputs.changeset_type }}
        Changeset message: ${{ inputs.changeset_message }}
    secrets:
      TEST_ENV: ${{ secrets.TEST_ENV }}
      KONFIG_API_KEY: ${{ secrets.KONFIG_API_KEY }}
      SUBMODULE_DEPLOY_KEY_PHP: ${{ secrets.SUBMODULE_DEPLOY_KEY_PHP }}
      SUBMODULE_DEPLOY_KEY_PHP7: ${{ secrets.SUBMODULE_DEPLOY_KEY_PHP7 }}
